In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/atlantico-academy/equipe6-2024.2/master/data/raw/Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df.to_csv("../data/raw/data.csv", index=False)

In [8]:
import pandas as pd

# Criando o dicionário com as descrições das variáveis
dicionario = pd.DataFrame([
    {
        "variavel": "RowNumber",
        "descricao": "Número da linha, usado como identificador sequencial",
        "tipo": "quantitativa",
        "subtipo": "discreta"
    },{
        "variavel": "CustomerId",
        "descricao": "Identificador único do cliente",
        "tipo": "quantitativa",
        "subtipo": "discreta"
    },{
        "variavel": "Surname",
        "descricao": "Sobrenome do cliente",
        "tipo": "qualitativa",
        "subtipo": "nominal"
    },{
        "variavel": "CreditScore",
        "descricao": "Pontuação de crédito do cliente",
        "tipo": "quantitativa",
        "subtipo": "discreta"
    },{
        "variavel": "Geography",
        "descricao": "País de residência do cliente",
        "tipo": "qualitativa",
        "subtipo": "nominal"
    },{
        "variavel": "Gender",
        "descricao": "Gênero do cliente (Male/Female)",
        "tipo": "qualitativa",
        "subtipo": "nominal"
    },{
        "variavel": "Age",
        "descricao": "Idade do cliente",
        "tipo": "quantitativa",
        "subtipo": "discreta"
    },{
        "variavel": "Tenure",
        "descricao": "Tempo de permanência do cliente no banco (em anos)",
        "tipo": "quantitativa",
        "subtipo": "discreta"
    },{
        "variavel": "Balance",
        "descricao": "Saldo da conta do cliente",
        "tipo": "quantitativa",
        "subtipo": "contínua"
    },{
        "variavel": "NumOfProducts",
        "descricao": "Número de produtos que o cliente possui no banco",
        "tipo": "quantitativa",
        "subtipo": "discreta"
    },{
        "variavel": "HasCrCard",
        "descricao": "Indica se o cliente possui um cartão de crédito (1) ou não (0)",
        "tipo": "qualitativa",
        "subtipo": "binária"
    },{
        "variavel": "IsActiveMember",
        "descricao": "Indica se o cliente é um membro ativo (1) ou não (0)",
        "tipo": "qualitativa",
        "subtipo": "binária"
    },{
        "variavel": "EstimatedSalary",
        "descricao": "Salário estimado do cliente",
        "tipo": "quantitativa",
        "subtipo": "contínua"
    },{
        "variavel": "Exited",
        "descricao": "Indica se o cliente deixou o banco (1) ou não (0)",
        "tipo": "qualitativa",
        "subtipo": "binária"
    }
])

# Salvando o dicionário em um arquivo CSV
dicionario.to_csv('../data/external/dictionary.csv', index=False)

# Exibindo o dicionário
dicionario

,variavel,descricao,tipo,subtipo
0,RowNumber,"Número da linha, usado como identificador sequ...",quantitativa,discreta
1,CustomerId,Identificador único do cliente,quantitativa,discreta
2,Surname,Sobrenome do cliente,qualitativa,nominal
3,CreditScore,Pontuação de crédito do cliente,quantitativa,discreta
4,Geography,País de residência do cliente,qualitativa,nominal
5,Gender,Gênero do cliente (Male/Female),qualitativa,nominal
6,Age,Idade do cliente,quantitativa,discreta
7,Tenure,Tempo de permanência do cliente no banco (em a...,quantitativa,discreta
8,Balance,Saldo da conta do cliente,quantitativa,contínua
9,NumOfProducts,Número de produtos que o cliente possui no banco,quantitativa,discreta
10,HasCrCard,Indica se o cliente possui um cartão de crédit...,qualitativa,binária
11,IsActiveMember,Indica se o cliente é um membro ativo (1) ou n...,qualitativa,binária
12,EstimatedSalary,Salário estimado do cliente,quantitativa,contínua
13,Exited,Indica se o cliente deixou o banco (1) ou não (0),qualitativa,binária